Add boilderplate for Go lambda
- Added empty Go Lambda function for the AWS skill
- Updated Makefile to vet and build Lambda
- Updated README

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -3,6 +3,13 @@
 # Git pre-commit hook
 #
 
+if ! make vet; then
+    echo ''
+    echo '❌  [FAIL] Vet has failed'
+    echo ''
+    exit 1
+fi
+
 if ! make build; then
     echo ''
     echo '❌  [FAIL] Build has failed'
